DELETE FROM STATION;
DELETE FROM TRAIN;

INSERT INTO STATION (ID, NAME) VALUES (1, 'Москва Окт');
INSERT INTO STATION (ID, NAME) VALUES (2, 'Москва Курс');
INSERT INTO station (ID, NAME) VALUES (3, 'St.Peterburg');

INSERT INTO TRAIN (ID, TRAIN_NUMBER, NAME) VALUES (1, '115А', 'С-Пет-Лад — Адлер');
INSERT INTO TRAIN (ID, TRAIN_NUMBER, NAME) VALUES (2, '029А', 'С-Петер-Гл — Москва Окт');
INSERT INTO TRAIN (ID, TRAIN_NUMBER, NAME) VALUES (3, '031А', 'С-Петер-Гл — Москва Курс');
INSERT INTO TRAIN (ID, TRAIN_NUMBER, NAME) VALUES (4, '037А', 'С-Петер-Гл — Москва Окт');


INSERT INTO ROUTE (ID, DEPARTURE_DATE, ARRIVAL_DATE, FROM_STATION_ID, TO_STATION_ID, TRAIN_ID) VALUES (1, '2017-09-17 12:00:00', '2017-09-17 18:00:00', 3, 1, 2);
INSERT INTO ROUTE (ID, DEPARTURE_DATE, ARRIVAL_DATE, FROM_STATION_ID, TO_STATION_ID, TRAIN_ID) VALUES (2, '2017-09-17 11:30:00', '2017-09-17 18:30:00', 1, 3, 3);
