DROP TABLE IF EXISTS STATION;
DROP TABLE IF EXISTS TRAIN;
DROP TABLE IF EXISTS ROUTE;
DROP TABLE IF EXISTS TICKET_TYPE;
DROP TABLE IF EXISTS TICKET_STATE;
DROP TABLE IF EXISTS TICKET;

CREATE TABLE STATION (
  ID   IDENTITY PRIMARY KEY,
  NAME VARCHAR NOT NULL
);

CREATE TABLE TRAIN (
  ID           IDENTITY PRIMARY KEY,
  NAME         VARCHAR NOT NULL,
  TRAIN_NUMBER VARCHAR NOT NULL
);


CREATE TABLE ROUTE (
  ID              IDENTITY PRIMARY KEY,
  TRAIN_ID        INTEGER   NOT NULL,
  FROM_STATION_ID INTEGER   NOT NULL,
  TO_STATION_ID   INTEGER   NOT NULL,
  DEPARTURE_DATE  TIMESTAMP NOT NULL,
  ARRIVAL_DATE    TIMESTAMP NOT NULL,
  FOREIGN KEY (FROM_STATION_ID) REFERENCES STATION (ID) ON DELETE CASCADE,
  FOREIGN KEY (TO_STATION_ID) REFERENCES STATION (ID) ON DELETE CASCADE,
  FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN (ID) ON DELETE CASCADE
);

CREATE TABLE TICKET (
  ID         IDENTITY PRIMARY KEY,
  ROUTE_ID   INTEGER NOT NULL,
  SET_NUMBER INTEGER NOT NULL,
  price      BIGINT,
  STATE      VARCHAR(255),
  TYPE       VARCHAR(255),
  FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE (ID) ON DELETE CASCADE
);



